AIRFLOW: False
MODEL_TYPE: logistic
DATASET:
  PATH: .tmp/dataset/dataset_train_v2.csv
  TEST_SIZE: 0.2
  RANDOM_STATE: 42
  ID_COL_NAME: SK_ID_CURR
  TARGET_COL_NAME: TARGET
  SAMPLER: null
GRID_SEARCH: true
TUNE_THRESHOLD: false
MULTIPROCESSING: true
