AIRFLOW: False
MODEL_TYPE: xgboost
DATASET:
  PATH: .tmp/dataset/dataset_train.csv
  TEST_SIZE: 0.2
  RANDOM_STATE: 42
  ID_COL_NAME: SK_ID_CURR
  TARGET_COL_NAME: TARGET
  SAMPLER: composite
GRID_SEARCH: true
TUNE_THRESHOLD: true
MULTIPROCESSING: false
