services:
    # API Container
    api:
        platform: linux/amd64
        container_name: inference_api
        build:
            context: .
            dockerfile: dockerfiles/Dockerfile.api
        image: inference_api
        pull_policy: build
        ports:
            - 8000:8000
        profiles:
            - full
            - api
    # Streamlit Container
    client:
        container_name: streamlit
        platform: linux/amd64
        build:
            context: .
            dockerfile: dockerfiles/Dockerfile.streamlit
        image: streamlit
        pull_policy: build
        volumes:
            - ./client/.cache:/usr/src/app/.cache
        ports:
            - 8501:8501
        profiles:
            - full
            - client
