FROM apache/airflow:2.10.0-python3.10

# Install Dependencies
RUN pip install -U pip --upgrade pip
COPY ./airflow/requirements.txt .
RUN pip install -r requirements.txt

COPY ./package /opt/airflow/package
RUN pip install -e /opt/airflow/package/

USER root
RUN apt-get update && apt-get install -y libgomp1
USER airflow