FROM amd64/python:3.10.14-slim

# install packages
RUN apt-get update &&\
    apt-get install -y git wget &&\
    rm -rf /var/lib/apt/lists/*

# Install Dependencies
RUN pip install -U pip --upgrade pip &&\
    pip install mlflow==2.15.1 boto3 psycopg2-binary

# install miniIO client
RUN cd /tmp &&\
    wget https://dl.min.io/client/mc/release/linux-amd64/mc &&\
    chmod +x mc &&\
    mv mc /usr/bin/mc

# Port
EXPOSE 5001