FROM amd64/python:3.10.14-slim

# Working Directory
WORKDIR /usr/src/app

# Install Packages
RUN apt-get update && \
    apt-get install libgomp1

# Copy files
COPY ./package /usr/src/package
COPY .env .
COPY ./inference_api .

# Install Dependencies
RUN pip install --upgrade pip &&\
    pip install -e .

# Start
EXPOSE 8000
ENTRYPOINT fastapi run inference_api/app.py